# Numpy Basics <hr style="border:2.5px solid #126782"></hr>

<b>Roan Gayl Ydrian B. Agustin</b>
<br>CpE - 2A

In [1]:
# imports and packages
import numpy as np

# 1D Array

In [2]:
my_array = [1,2,3]

In [7]:
type(my_array)

numpy.ndarray

In [6]:
my_array = np.array([1,2,3])

In [8]:
np.shape(my_array)

(3,)

# 2D Array

In [9]:
import numpy as np

In [22]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.shape(my_array)

(2, 3)

In [25]:
my_array.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [23]:
trans_array = my_array.T


In [26]:
np.shape(trans_array)

(3, 2)

np.mean()
np.median()
stata.mode()
np.min()
np.max()
np.sum
np.
axis=0
axis=1

In [27]:
np.sum(trans_array,axis=0)

array([ 6, 15])

In [28]:
np.sum(trans_array,axis=1)

array([5, 7, 9])

# Measure of Central Tendency




In [30]:
resistance = np.array ([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8],
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan]
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [32]:
np.nanmean(resistance,axis=1)

array([ 9.4 , 10.75])