# Numpy Basics <hr style="border:2.5px solid #126782"></hr>

<b>Roan Gayl Ydrian B. Agustin</b>
<br>CpE - 2A

In [58]:
# imports and packages
import numpy as np
from scipy import stats
from statistics import multimode

# 1D Array

In [26]:
my_array = [1,2,3]

In [27]:
type(my_array)

list

In [28]:
my_array = np.array([1,2,3])

In [29]:
np.shape(my_array)

(3,)

# 2D Array

In [30]:
import numpy as np

In [31]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.shape(my_array)

(2, 3)

In [33]:
my_array.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
trans_array = my_array.T


In [35]:
np.shape(trans_array)

(3, 2)

np.mean()
np.median()
stata.mode()
np.min()
np.max()
np.sum
np.
axis=0
axis=1

In [36]:
np.sum(trans_array,axis=0)

array([ 6, 15])

In [37]:
np.sum(trans_array,axis=1)

array([5, 7, 9])

# Measure of Central Tendency




In [50]:
resistance = np.array ([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8],
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan]
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [51]:
np.shape(resistance)

(2, 11)

In [52]:
resistance.T

array([[10.6, 10.1],
       [ 9.1, 11. ],
       [ 9.3,  9.1],
       [ 9.8, 20. ],
       [10.5,  9.2],
       [10.4, 10.8],
       [ 9.5,  9.9],
       [11. ,  9.2],
       [10.4,  9.1],
       [ 3. ,  9.1],
       [ 9.8,  nan]])

# Mean

In [53]:
np.mean(resistance,axis=0)

array([10.35, 10.05,  9.2 , 14.9 ,  9.85, 10.6 ,  9.7 , 10.1 ,  9.75,
        6.05,   nan])

In [54]:
np.mean(resistance,axis=1)

array([9.4, nan])

In [55]:
#Mean 
np.nanmean(resistance,axis=1)

array([ 9.4 , 10.75])

# Median 

In [56]:
jag_median = np.nanmedian(resistance,axis=1)[0]
pan_median = np.nanmedian(resistance,axis=1)[1]

print (f'Jaguar_median = {jag_median:.2f} ohms')
print (f'Panther_median = {pan_median:.2f} ohms')



Jaguar_median = 9.80 ohms
Panther_median = 9.55 ohms


# Mode

In [59]:
# Mode
stats.mode(resistance, axis=1) 

ModeResult(mode=array([9.8, 9.1]), count=array([2, 3]))

In [60]:
my_array = [1,1,2,2,3,4,5]
multimode(my_array)

[1, 2]

In [61]:
jag_res = resistance[0]

print ("jaguar mode:")
for i  in multimode(jag_res):
    print (f'{i} ohms') 

jaguar mode:
9.8 ohms
10.4 ohms


In [62]:
pan_res = resistance[0]

print ("panther mode:")
for i  in multimode(pan_res):
    print (f'{i} ohms') 

panther mode:
9.8 ohms
10.4 ohms


# Measure of Variability 

In [64]:
# Jaguar VS Panther
resistance = np.array ([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8,], 
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan]
    ])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

# Range

In [65]:
res_max = np.nanmax(resistance,axis=1)
res_min = np.nanmin(resistance,axis=1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [66]:
print (f' Jaguar range = {res_range[0]:.2f} ohms')
print (f' Panther range = {res_range[1]:.2f} ohms')

 Jaguar range = 8.00 ohms
 Panther range = 10.90 ohms


# Quartiles 

In [67]:

# 1st Quartile
res_Q1 = np.nanpercentile(resistance,25,axis=1)
res_Q1

array([9.4  , 9.125])

In [68]:
# 2nd Quartile
res_Q2 = np.nanpercentile(resistance,50,axis=1)
res_Q2

array([9.8 , 9.55])

In [69]:
# 3rd Quartile
res_Q3 = np.nanpercentile(resistance,75,axis=1) 
res_Q3

array([10.45 , 10.625])

In [75]:
# 4th Quartile
res_Q4 = np.nanpercentile(resistance,100,axis=1) 
res_Q4

array([11., 20.])

# Interquartile Range (IQR)

In [70]:
print (f'Jaguar IQR = {res_Q3[0] - res_Q1[0]:.2f} ohms')
print (f'Panther IQR = {res_Q3[1] - res_Q1[1]:.2f} ohms')

Jaguar IQR = 1.05 ohms
Panther IQR = 1.50 ohms


# Variance

In [71]:
res_var = np.nanvar(resistance,axis=1)
res_var 

array([4.41818182, 9.9745    ])

In [72]:
print (f'Jaguar Variance = {res_var[0]:.2f} ohms')
print (f'Panther Variance = {res_var[1]:.2f} ohms')

Jaguar Variance = 4.42 ohms
Panther Variance = 9.97 ohms


# Standard Deviation 

In [73]:
res_std = np.nanstd(resistance,axis=1)
res_std

array([2.10194715, 3.15824318])

In [74]:
print (f'Jaguar Standard Deviation = {res_std[0]:.2f} ohms')
print (f'Panther Standard Deviation = {res_std[1]:.2f} ohms')   

Jaguar Standard Deviation = 2.10 ohms
Panther Standard Deviation = 3.16 ohms
